I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00gamemenu.rpy", line 170, in script
    $ ui.interact()
  File "renpy/common/00gamemenu.rpy", line 170, in <module>
    $ ui.interact()
Exception: DynamicImage ['gui/confirm_frame.png', 'gui/frame.png']: could not find image. ('gui/confirm_frame.png', 'gui/frame.png')

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00gamemenu.rpy", line 170, in script
    $ ui.interact()
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00gamemenu.rpy", line 170, in <module>
    $ ui.interact()
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\display\core.py", line 3579, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\display\core.py", line 4052, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 1 more time]
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\display\screen.py", line 481, in visit_all
    self.child.visit_all(callback, seen=None)
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\display\core.py", line 681, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\display\core.py", line 671, in visit_all
    for d in self.visit():
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\display\image.py", line 785, in visit
    self.find_target()
  File "C:\Users\ShiroRey\Desktop\RenPy\renpy-8.1.1-sdk\renpy\display\image.py", line 683, in find_target
    raise Exception(error)
Exception: DynamicImage ['gui/confirm_frame.png', 'gui/frame.png']: could not find image. ('gui/confirm_frame.png', 'gui/frame.png')

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
Alice in the Underworld 
Tue Jan 30 19:52:19 2024
